✨(app) create a redis-sentinel application
openfun/arnold pull request #402
Opened 2019-11-28 16:09 UTC by lunika

## Purpose

we choose to use the redis-operator
(https://github.com/spotahome/redis-operator) to deploy a redis
configured with sentinel. Only one OpenShift is used and deployed as a
Service.

## Proposal

- [x] implement the redis-sentinel app

2019-11-29 13:21 UTC, jmaupetit approved these changes
Great work!

![](https://media0.giphy.com/media/IUZtGhVO8hZ6w/giphy.gif)

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/vars/settings.yml
> +is_blue_green_compatible: False
```suggestion
is_blue_green_compatible: false
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/templates/services/app/svc.yml.j2
> +deploy at the same time of other OpenShift Service, this is why we decided to created in this file.
Can you indent this comment in the block?

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/templates/services/app/svc.yml.j2
> +This template is not relative to an OpenShift Service object but to a RedisFailover one.
```suggestion
Disclaimer: this template is not relative to an OpenShift Service object but to a RedisFailover object.
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/templates/services/app/svc.yml.j2
> +RedisFailover is part of redis-operator (https://github.com/spotahome/redis-operator) ans must be
```suggestion
RedisFailover is part of the redis-operator (https://github.com/spotahome/redis-operator) and must be
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/templates/services/app/svc.yml.j2
> +  # name of the service should be host name in edxapp configuration prefixed by rfs- : rfs-redis-sentinel
```suggestion
  # Nota bene: the name of the service should be the host name in edxapp configuration,
  # prefixed by "rfs-", e.g. "rfs-redis-sentinel"
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/vars/all/main.yml
> +# This setting can be found in the project annotation
```suggestion
# The following settings can be found in the project's annotation.
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/vars/all/main.yml
> +# to retrieve them run oc project {{ project_name }} -o yaml
```suggestion
# To retrieve them run the following command:
#   $ oc project {{ project_name }} -o yaml
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/vars/all/main.yml
> +# then copy the value of the annotation openshift.io/sa.scc.supplemental-groups
```suggestion
# then copy values of the `openshift.io/sa.scc.supplemental-groups` annotation
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/vars/all/main.yml
> +# them in this list. One configuration is a new entry
```suggestion
# them in this list with one configuration per item, e.g.:
```

2019-11-29 13:21 UTC, jmaupetit commented on apps/redis-sentinel/vars/all/main.yml
> +# them in this list. One configuration is a new entry
```suggestion
# them in this list with one configuration per item, e.g.:
```

2019-11-29 13:22 UTC, jmaupetit commented
Even tho, we will need a new PR allowing to use Redis sentinel in `edxapp` (see worker probes).

2019-12-03 13:34 UTC, jmaupetit requested changes
In fact we need to fix `edxapp` workers probes that would be broken if we switch to redis sentinel. See https://github.com/openfun/arnold/blob/master/apps/edxapp/templates/services/cms/_dc_base.yml.j2#L96

2019-12-03 16:22 UTC, lunika commented
> In fact we need to fix `edxapp` workers probes that would be broken if we switch to redis sentinel. See https://github.com/openfun/arnold/blob/master/apps/edxapp/templates/services/cms/_dc_base.yml.j2#L96

This should be done in an other PR ? This PR just target the creation of a new app

2019-12-03 17:14 UTC, jmaupetit commented
> This PR just target the creation of a new app

2019-12-04 09:50 UTC, lunika commented
Ok so the only solution I found for now is to transform the command with this:

```
celery -A lms.celery inspect ping -d celery@{{ celery_worker.name }}.%$(hostname)
```

WDYT @sampaccoud @jmaupetit

2019-12-04 12:07 UTC, sampaccoud commented
@lunika I would say that if we want the edxapp healthcheck to validate that redis is working it should be done via the edxapp healthcheck endpoint? But I'm not really aware of existing probes :man_shrugging:

2019-12-04 12:33 UTC, lunika commented
> @lunika I would say that if we want the edxapp healthcheck to validate that redis is working it should be done via the edxapp healthcheck endpoint? But I'm not really aware of existing probes man_shrugging

This probe is not used by the wsgi application but by very worker deployed.

2019-12-04 13:19 UTC, sampaccoud commented
Then we should add a small management command in edxapp that checks the redis connection (with or without sentinel depending on the settings the same way as Celery or django-redis-session are connecting to redis...). I would make a simple command that writes a value to redis and reads it again... WDYT?

2019-12-04 13:31 UTC, jmaupetit commented
Loading a management command with the `edx`stack is too heavy for a health check. That was our first attempt and it proved to be unusable.

2019-12-04 13:36 UTC, jmaupetit commented
> Ok so the only solution I found for now is to transform the command with this:
> 
> ```
> celery -A lms.celery inspect ping -d celery@{{ celery_worker.name }}.%$(hostname)
> ```
> 
> WDYT @sampaccoud @jmaupetit

Have you tried it with `time` in a worker pod to evaluate its responsiveness.

2019-12-04 16:31 UTC, lunika commented
``` bash
$ time celery -A lms.celery inspect ping -d celery@lms-default.%$(hostname)
-> celery@lms-default.%edxapp-lms-default-worker-d-190717-13h37m29s-2-sf9qm: OK
        pong

real	0m1.211s
user	0m0.992s
sys	0m0.620s
```

2019-12-04 18:00 UTC, jmaupetit commented
Did you run it multiple times (at least 3) to check execution time "standard deviation"? IMO 1.2s is not acceptable for such probe.

2019-12-04 20:58 UTC, lunika commented
> Did you run it multiple times (at least 3) to check execution time "standard deviation"? IMO 1.2s is not acceptable for such probe.

Yes I run it multiple time and this is one the best time I have.

2019-12-05 14:12 UTC, jmaupetit commented
So it's a dead end.

2019-12-06 09:46 UTC, jmaupetit commented on CHANGELOG.md
> +- probes on edxapp workers. They are too slow to be run
This is not true: the real problem is that existing probes are not compatible with redis sentinel and alternative probes based on Django management commands or Celery using Django settings are too slow to be considered as a relevant alternative. You must add that this is a temporary removal until we implement a new efficient probe.

2019-12-06 10:30 UTC, jmaupetit commented on CHANGELOG.md
> +- probes on edxapp workers. Existing probes are not compatible with redis sentinel.
```suggestion
- Probes on edxapp workers. Existing probes are not compatible with redis sentinel.
```

2019-12-06 10:30 UTC, jmaupetit commented on CHANGELOG.md
> +  using Django settings, doing this is too slow to be considered as a relevant alternative.
```suggestion
  using Django settings, but doing so is too slow to be considered as a relevant alternative.
```

2019-12-06 10:30 UTC, jmaupetit commented on CHANGELOG.md
> +  This removal is temporary, a new solution must be developed soon.
```suggestion
  This removal is temporary, a new solution will be developed soon.
```

2019-12-06 13:04 UTC, jmaupetit approved these changes

2019-12-06 14:27 UTC, merged